# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyIDA\widgets\CreateVarDialog\create_var_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateVarDialog(object):
    def setupUi(self, CreateVarDialog):
        CreateVarDialog.setObjectName("CreateVarDialog")
        CreateVarDialog.resize(714, 631)
        CreateVarDialog.setStyleSheet("background-color: rgb(34, 44, 40);\n"
"color: rgb(248, 248, 248);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateVarDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(CreateVarDialog)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.class_cb = QtWidgets.QComboBox(CreateVarDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_cb.sizePolicy().hasHeightForWidth())
        self.class_cb.setSizePolicy(sizePolicy)
        self.class_cb.setEditable(True)
        self.class_cb.setObjectName("class_cb")
        self.horizontalLayout_2.addWidget(self.class_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(CreateVarDialog)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.old_var_name_edit = QtWidgets.QLineEdit(CreateVarDialog)
        self.old_var_name_edit.setInputMask("")
        self.old_var_name_edit.setObjectName("old_var_name_edit")
        self.horizontalLayout_4.addWidget(self.old_var_name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(CreateVarDialog)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.array_index_edit = QtWidgets.QLineEdit(CreateVarDialog)
        self.array_index_edit.setInputMask("")
        self.array_index_edit.setObjectName("array_index_edit")
        self.horizontalLayout_6.addWidget(self.array_index_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(CreateVarDialog)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.newvar_name_edit = QtWidgets.QLineEdit(CreateVarDialog)
        self.newvar_name_edit.setObjectName("newvar_name_edit")
        self.horizontalLayout_3.addWidget(self.newvar_name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.source_text_edit = QtWidgets.QTextEdit(CreateVarDialog)
        self.source_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.source_text_edit.setObjectName("source_text_edit")
        self.horizontalLayout_5.addWidget(self.source_text_edit)
        self.verticalScrollBar = QtWidgets.QScrollBar(CreateVarDialog)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_5.addWidget(self.verticalScrollBar)
        self.dest_text_edit = QtWidgets.QTextEdit(CreateVarDialog)
        self.dest_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dest_text_edit.setObjectName("dest_text_edit")
        self.horizontalLayout_5.addWidget(self.dest_text_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(CreateVarDialog)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(CreateVarDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CreateVarDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateVarDialog)

    def retranslateUi(self, CreateVarDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateVarDialog.setWindowTitle(_translate("CreateVarDialog", "Create variable"))
        self.label.setText(_translate("CreateVarDialog", "Class name:"))
        self.label_3.setText(_translate("CreateVarDialog", "old var name:"))
        self.label_4.setText(_translate("CreateVarDialog", "array index"))
        self.label_2.setText(_translate("CreateVarDialog", "new var:"))
        self.save_btn.setText(_translate("CreateVarDialog", "Save"))
        self.cancel_btn.setText(_translate("CreateVarDialog", "Cancel"))

